# Generated by Django 2.2.2 on 2020-11-07 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='決済手段名')),
                ('date', models.DateField(verbose_name='引き落とし日')),
            ],
            options={
                'verbose_name_plural': 'Card',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリー')),
                ('date', models.DateField(verbose_name='発生日')),
                ('cash', models.BooleanField(verbose_name='現金決済')),
                ('comment', models.CharField(max_length=40, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='topbudget.Card', verbose_name='その他決済')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Spending',
            },
        ),
    ]
