# Generated by Django 2.2.2 on 2020-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbudget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='支出額'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.CharField(max_length=40, null=True, verbose_name='コメント'),
        ),
    ]
