# Generated by Django 2.2.2 on 2020-11-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topbudget', '0003_auto_20201108_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topbudget.Card', verbose_name='その他決済'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='コメント'),
        ),
    ]
